### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [dstathis/optprompt#8]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.4.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary optprompt -w /tmp/ext optprompt==0.4.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting optprompt==0.4.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/816/04503ddb14e02/optprompt-0.4.0.tar.gz (2.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-m8dmzz7j/optprompt/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-m8dmzz7j/optprompt/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-m8dmzz7j/optprompt/pip-egg-info
         cwd: /tmp/pip-wheel-m8dmzz7j/optprompt/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-m8dmzz7j/optprompt/setup.py", line 20, in <module>
        install_requires=open(
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-m8dmzz7j/optprompt/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by dstathis** [comment]
Thanks for the PR
